title: Thibaut Arnoulx de Pirey
logo: /assets/img/amb_spiceestew_2.png
description: Contact Faculty of Physics - Lidow Physics Complex - Technion - Office: 312 - E-mail: t.depirey [at] campus [dot] technion [dot] ac [dot] il - Scholar 
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
